# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoRondônia
                                 A QGIS plugin
 Georondonia
 Generated by Plugin Builder: -------------------
                              -------------------
        begin                : 2024-11-13
        copyright            : (C) 2024 by GeoRondônia
        email                : lab.georondonia@ifro.edu.br
 ***************************************************************************/
"""

__author__ = 'Maik Rodrigues'
__date__ = '2024-11-13'
__copyright__ = '(C) 2024 by Maik Rodrigues'

def classFactory(iface):
    from .Georondonia import GeorondoniaPlugin
    return GeorondoniaPlugin()
